### ISSUE TITLE
Create/Delete localstorage key on Firefox 17 doesn't generate an event

### ISSUE THREAD

**Issue by nialscorva** [ozone-development/ozp-iwc#123]
On Firefox 17, and possibly other browsers, a `localstorage.setItem() immediately followed by a `localStorage.removeItem()` does not generate a `storage` event on other contexts.  This breaks the communication between tabs for the IWC.  According to the Web Storage spec, the event should be sent, and Firefox 24 and later does seem to send this event.

Acceptance criteria:
-  Determine which browsers properly send the event.  For those browsers, use the current behavior.
-  For Firefox 17 and other browsers, do not immediately delete the key.  Call `localStorage.removeItem()` in the `storage` event handler.  This will minimize the time that the storage space is occupied and prevent the need to set a timer.  

Removing a non-existent storage item should not throw an exception, but if it does it should be ignored.

**Comment by Kevin-K** [comment]
PR #189 fixed keyword issues and added some better IE compatibility.

Further issues for IE see #188
