### ISSUE TITLE
Data.api Content-Type should being sent when persisting

### ISSUE THREAD

**Issue by Kevin-K** [ozone-development/ozp-iwc#159]
Regardless of `contentType` assigned to the api node, the AJAX request header will send 
```
Content-Type:text/plain;charset=UTF-8
```

**Comment by nialscorva** [comment]
Just to note, the data API always saves its values wrapped in `application/vnd.ozp-iwc-data-object+json`, thus the HTTP "ContentType" should always be that.  Within that wrapper, there's a `contentType` field that should represent the type of the `entity` field.

**Comment by Kevin-K** [comment]
Shedding light on an old issue:
* **(As expected)**: Internal (node entity corresponding) contentType is written when a set-like action is called:
`client.data().set("/foo",{contentType: "application/json", entity: {} });`

* **(Not as expected)**: ozpIwc.util.ajax checks for config.headers to be an array, rather the ajaxPersistenceQueue passes in an object thus `text/plain;charset=UTF-8` is always used.
```
 if (Array.isArray(config.headers)) {
            config.headers.forEach(function(header) {
                if(header.name ==="Content-Type"){
                    setContentType = false;
                }
                request.setRequestHeader(header.name, header.value);
            });
        }
```
