### ISSUE TITLE
Investigate high latencies under moderate load under Internet Explorer 9 & 10

### ISSUE THREAD

**Issue by nialscorva** [ozone-development/ozp-iwc#188]

**Comment by Kevin-K** [comment]
Some findings from working on IE 9 compatibility, primarily to reduce load:

* Move to a flow controlled packet transmission where upon attempting to send a packet the bus waits N ms for further packets to be transmitted and packages them together.

* Names api heartbeats can skip the `ok` response packet to reduce traffic

* Names api heartbeats should be wrapped up in the watchdog into single packets to reduce traffic

**Comment by nialscorva** [comment]
* Flow control is #202 
* Skipping the `ok` response is covered by #205
* Watchdog summarization is #200

**Comment by nialscorva** [comment]
Added tester for localstorage latencies to the demo.  It runs on "localhost:15007".

Testing indicates that IE 9 increasingly falls behind processing localstorage events at less than 10 events per second in very simple cases.  

IE 11 and all tested versions of Firefox & Chrome do not seem to have this problem.

IE 10 still needs to be tested.
