### ISSUE TITLE
Treat the API endpoints as a flat list instead of a tree

### ISSUE THREAD

**Issue by nialscorva** [ozone-development/ozp-iwc#197]
In the API's "loadDataFromServer" series of calls, treat the endpoints as a flat list instead of the head of a tree.  This eliminates the recursive crawl and the fragile counting that sometimes prevents the data.api from knowing that it's ready to start work.

**Comment by wallace-m** [comment]
#194 also contains the solution for this issue.  It is completed with a pull-request, waiting review.
