### ISSUE TITLE
"BulkGet" action for APIs

### ISSUE THREAD

**Issue by nialscorva** [ozone-development/ozp-iwc#201]
BulkGet" action for APIs to get all values who have keys that match a pattern.  The N+1 antipattern of "list" N items and N "get"s on those items exists in the IWC and would reduce a lot of traffic for applications starting up.  e.g. the debugger lists all keys and does individual gets on them, causing a flood of 500+ packets within a second or two at startup.

For a request of form
```
{
  "action": "bulkGet",
  "resource:": "/foo"
}
```

The response entity should be a table of resources and the packet fragment that would have been sent in response to a GET on that packet.  e.g.
```
[
  {
    contentType: "application/json",
    eTag: 23,
    entity: { "bar": 20}
  },{
    contentType: "text/plain",
    eTag: 1,
    entity: "Hello World!"
  }
]
```

**Comment by wallace-m** [comment]
The solution returns a list of matching nodes (by prefix on resource).
The list is returned like a list version of 'handleGet': each matching node is processed by '.toPacket()' and pushed into the list.
So it is like the 'get' function, but it is not exactly like the sample data above.

**Comment by nialscorva** [comment]
Add unit tests for:
*  correctly returns varied contentTypes 
*  correctly returns entities
*  correctly returns an empty array if no keys match

Add a client tests that use `client.api("data.api").bulkGet("/foo")` to make sure that the client builds the right interface.

**Comment by wallace-m** [comment]
New unit tests completed, and data.api test updated.
handleBulkget returns an array of node.toPacket().
