### ISSUE TITLE
Add an "respondOn" flag to the packet spec

### ISSUE THREAD

**Issue by nialscorva** [ozone-development/ozp-iwc#205]
Many actions don't require a response, so we can reduce network traffic by skipping them when not needed.

* add an optional "respondOn" enum with values "all","error","none" to the packet schema, default value is "all".
* Recipients SHOULD honor the respondOn field.
* Recipients MUST interpret a missing "respondOn" as "all".
* Senders MUST gracefully handle unexpected responses.
* Client's `send()` MUST not automatically add the field.
  * The API-builder style Client MAY add the "respondOn" field if appropriate.  It SHOULD avoid sending a value of "all" if possible, since that's the default value.
* modify the APIs to respect "respondOn" values:
  * "error", "none" -- do not send "OK" responses
  * "none" -- do not send any response
* Modify the WatchDog to to have "respondOn: none".

**Comment by Kevin-K** [comment]
>* modify the APIs to respect "respondOn" values:
    * "error", "none" -- do not send "OK" responses
    * "none" -- do not send any response

Rather than make the API regulate the response, make the packet context's replyTo functionality filter responding. This gives more granular control over responding.

**Comment by Kevin-K** [comment]
>* Senders MUST gracefully handle unexpected responses.

ApiPromiseMixin triggers a `receive` event should an unexpected packet arrive.
