### ISSUE TITLE
IE9 ajax is denied

### ISSUE THREAD

**Issue by Kevin-K** [ozone-development/ozp-iwc#221]
Trying to load endpoints with the debugger:
>LOG: [ERROR] Could not load from api (ozp:user-data): Access is denied.
Error: Access is denied.

It seems the error is not a server response, rather IE9 drops the request on `request.open`. Is this a CORS related issue?

**Comment by Kevin-K** [comment]
This was found addressing #218 testing against a IE9 vm.

**Comment by rpokorny** [comment]
Do you have IWC and the backend running same domain or cross domain?

**Comment by Kevin-K** [comment]
Cross domain, thats right ie9 doesn't do CORS does it? 
I'll have to test against the backend locally I suppose

**Comment by rpokorny** [comment]
That is correct; IE9 effectively does not support CORS
