### ISSUE TITLE
Add the karma-runner to build scripts, add to Travis CI

### ISSUE THREAD

**Issue by nialscorva** [ozone-development/ozp-iwc#222]
Add tasks to grunt that run the unit, bus-integration, and client-integration tests using karma runner.
Update the .travis.yml so that Travis CI runs the unit, client-integration, and bus-integration tests appropriately.

**Comment by Kevin-K** [comment]
commit 53cc2e9621 
https://travis-ci.org/ozone-development/ozp-iwc/jobs/55866413
