### ISSUE TITLE
Fix crash caused by ozpIwc.log.logMsg when the dev console is open

### ISSUE THREAD

**Issue by nialscorva** [ozone-development/ozp-iwc#256]
```
//        var log = Function.prototype.bind.call(window.console.log, window.console);
//        log.apply(window.console,["["+level.name+"] "].concat(args));
```
This breaks Firefox if the the Firebug or dev tools console is open.  Fix it.  This seems to work on Firefox:
```
  window.console.log.apply(window.console,["["+level.name+"] "].concat(args));
```
IE might not support `apply()` on the console, see http://tobyho.com/2012/07/27/taking-over-console-log/

**Comment by Kevin-K** [comment]
Will not work in IE (tested 9,10,11)
``` 
window.console.log.apply(window.console, "Do you support me?"); 
```
>"Object doesn't support property or method 'apply'"
