### ISSUE TITLE
Intents malfunction on state passing

### ISSUE THREAD

**Issue by Kevin-K** [ozone-development/ozp-iwc#279]
the intentHandler node does not retain its `replyTo` property when serialized. This needs to be passed to the new leader in order for intent handler's to continue handling after the leadership changes.

**Comment by Kevin-K** [comment]
Handled in PR #280. Moved `replyTo` into intentHandler node's `entity`.

**Comment by Kevin-K** [comment]
Requires revisiting, if leader quits during an inflight intent it seems that the inflightIntent node is deleted (checking breakpoints it comes across in the death scream with a property of `deleted: true`.

**Comment by Kevin-K** [comment]
InFlightIntent node's are not deserialized properly. The in flight state machine is driven by the node directly and deserializing does not occur due to state transitions. Added a deserialize state to my local feature branch and node passing seems to cooperate now. Using as an intermediate fix so #208 can be addressed.

**Comment by Kevin-K** [comment]
**Testing Criteria:**

With no other IWC using applications open:
1) Open a location lister instance(1).
2) Open a second location lister instance(2).
3) Open 2 instances of location viewer.
4) In location lister (2):Create a listing, select it, and press `map`, the intent chooser will open (if not make sure pop ups are enabled, chrome will notify on location lister from (1) to enable popups.)
5) Close location lister (1).
6) Select a location viewer from the intent chooser and press `Use Once`.
7) If the location was marked with a green dot on one of the maps the test is passing.

**Comment by jal-vsi** [comment]
Verified Testing Criteria above in FF24 and CH36 using testUser1.  IE9 failed to allow Mapping (MyLocations Map) and IE11 failed to display viewer options in Intent Chooser.

**Comment by Kevin-K** [comment]
Due to #301 IE11 will not pass, so deeming the failure on IE11 not to be because of this issue. closing issue, if FF/CH are passing that is sufficient to deem this issue was fixed.

If trying to use IWC in IE11, see status of #301
