### ISSUE TITLE
Sample Backend 405's on PUT

### ISSUE THREAD

**Issue by Kevin-K** [ozone-development/ozp-iwc#284]
The [sample backend](https://github.com/ozone-development/ozp-data-schemas) is read-only. The grunt connect task does not have any middleware installed for POST requests.

Add middleware to return a 204, but drop the post data (a real backend would handle the POST, we just want to mock a real backend as we are just using a set of json files).

**Comment by Kevin-K** [comment]
**Testing:**
1.) `grunt connect-all
2.) open the sample bouncing balls. http://localhost:15001/
3.) Open dev-tools (F12) and go to network ( these directions are for chrome)

**Passing criteria:***
* All `PUT`/`DELETE` requests should have a `204` status with the payload being an info message stating `"The ozp-iwc sample backend drops all write actions."`
* No `405` errors occur

**Note:** the bouncing balls demo in the IWC is broken, no balls will appear. This testing criteria is purely for the sample backend connection

**Comment by mparizernc** [comment]
I was able to validate this locally. Currently the bouncing balls fail on develop because it can't find the IWC_client.

**Comment by Kevin-K** [comment]
Bouncing balls failing on develop would be a separate issue as this only pertains to local sample backend use. Although, the failure on develop has been noted and fixed.
