### ISSUE TITLE
Node collectors not collecting

### ISSUE THREAD

**Issue by Kevin-K** [ozone-development/ozp-iwc#293]
If a node is watched before creation it is registered as a watched node.
The same applies to collectors, although the collector registration logic blocks the registration if it is non-existant.

This will cause nodes that are watched by a client before they are created to not to broadcast updates pertaining to their collection (Location Lister bug).

**Comment by Kevin-K** [comment]
##Testing Criteria
This bug revolved around a resource that was not existent not receiving updates upon its creation.

To mark as passing: A fresh instance of an IWC deployment should allow the Location Lister widget to list locations after they are created:

1) Pull down ozp-iwc master
2) npm install && bower install
3) grunt serve
4) open http://localhost:13000/applications/locationLister
5) add a listing

If the listing shows in the application after the modal save without a browser refresh the bug is fixed.

**Comment by jal-vsi** [comment]
The alternate test of using Lister (add, edit, delete) works in IE11, FF24, CH36 but fails in IE9.

**Comment by Kevin-K** [comment]
:+1: current IWC roadmap isn't covering IE9, can be marked as done.
