### ISSUE TITLE
Centralize deployment configurations

### ISSUE THREAD

**Issue by Kevin-K** [ozone-development/ozp-iwc#325]
Currently users have to modify the iframe_peer.html, debugger.html, and intent_chooser.html when modifying backend root url, api configurations, ect.

Rather than modify each of these files, include an `iwc.conf.js` in the dist files that each reference.  Settings in this config file are not required, rather just overrides for default values in the IWC bus construction. This will effect current ozone build scripts, so updates will need to made to them as well.

This issue tracking includes documentation on the conf parameters.

@arw180 heads up about this. Not using OzoneConfig.js for this configuration file as it is purely IWC configurations and I don't want this to create deployment confusions as to the varied behavior among config files.

**Comment by Kevin-K** [comment]
Current implementation on [feature-deploy-config](https://github.com/ozone-development/ozp-iwc/feature-deploy-config).

Documentation/Testing underway. will be updating to version `1.1.0` with this change.

**Comment by emosher** [comment]
Came here from #267. :+1: I like it.

**Comment by arw180** [comment]
Makes sense, I like it. We'll just have to make sure we update our `dev-tools` and Jenkins scripts to `sed` that config file accordingly.

**Comment by Kevin-K** [comment]
Merged to master, will be releasing `1.10.0` after addressing #327. Can be built and ran locally with normal IWC grunt use: `grunt serve` initial doc updates can be found [here](https://github.com/ozone-development/ozp-iwc/blob/master/docs/iwc_guide/getting_started/bus_configuration/overview.md). Not on gitbook yet because it only updates on releases.

Additional config params are open for request

**Comment by Kevin-K** [comment]
Documentation updated to the gitbook [here](http://ozone-development.github.io/ozp-iwc/getting_started/bus_configuration/overview.html)

Closing as tagging `1.1.0`
