### ISSUE TITLE
Launching a widget from another widget

### ISSUE THREAD

**Issue by itaran** [ozone-development/ozp-iwc#385]
In OWF 7 the launcher (or preferences?) API allowed a widget to launch a different widget if that widget was not already launched.

Use Cases: 

User of Widget A wants to put data onto a map (or any other viewer widget), but the user hasn't launched the map.  When I click a map icon on Widget A, the Map Widget pops up for the user, and the data is sent to the map.

I use a Query Widget to get a list of results.  When I double click on a result another "Result Viewer" widget automatically comes up and displays the details about those results.

Does the existing IWC capability have the ability to replicate this capability.  If it does, please add this as its own section in the tutorial.  If the IWC doesn't allow this, it should be enhanced to make this possible.

**Comment by Kevin-K** [comment]
Currently there isn't any built-in functionality to handle this, since the opened application does not have direct knowledge of its application listing data from the backend.

Intent registration data on the server to allow applications to be launched to handle an intent was removed from the roadmap by the Ozone Team.

To handle the "is an application already open" question:
* In the application being opened (Map widget from use case) create a Data.api Resource with a  lifespan **bound to the application open** (when that application closes, the resource is deleted).

### Map Widget code
```
// use some unique name of the application as the resource name to avoid clashing.
var mapOpenRef = new iwc.data.Reference("/applications/open/com.example.mapWidget",{ 
  lifespan: "bound"
});

//The resource just needs creation and that is done by calling set"
mapOpenRef.set("Any value can be set here.");

//The resource will be deleted when this application closes because of lifespan: "bound"
```

By doing the above in the MapWidget, the Widget A from the use case can do the following to detect the widget:

### Widget A
``` 
// note the lifespan is not bound to this application. 
var mapOpenRef = new iwc.data.Reference("/applications/open/com.example.mapWidget");

// If the resource is gatherable the map is open
mapOpenRef.get().then(function(val){
    //mapWidget is open.
}).catch(function(err){
   //mapWidget is not open.
});

**Comment by itaran** [comment]
This particular issue has nothing to do with intents.  Thats the other issue.

This issue is simple.  Widget A is a widget that submits queries and gets a list of results.  When I double click on a result I want widget B to open and display the result.  Widget A already knows that it needs widget B.  It can find it by name.

Is there a way to find a widget by name or any other identifying info, launch it that way, and then pass some data to it.?

**Comment by Kevin-K** [comment]
Ah,

If the widget's unique_name from it's meta-data (the data used to list the widget) is known,
you can replicate the find by name functionality of owf7 like so:
>Is there a way to find a widget by name or any other identifying info ...

```
var widgetBRef = new iwc.system.Reference("/application/"+UNIQUE_NAME);
```
>... launch it that way, and then pass some data to it.?

You can pass launch data with the launch call:
```
var dataToPass = 123;
widgetBRef.launch(dataToPass);
```

Then in widgetB's code you can gather the launch data with the ozpIwc.Client instance (iwc):
```
var iwc = new ozpIwc.Client(...);

iwc.getLaunchData().then(function(launchData){
  // launchData holds 123
});
```

The gitbook hasn't been updated with the launch changes, but here is the old [approach](http://ozone-development.github.io/ozp-iwc/1.2.1/gitbook/client/apis/system/launch.html).

**Comment by Kevin-K** [comment]
Docs updated:
Check out [this section of the gitbook](http://ozone-development.github.io/ozp-iwc/1.2.2/gitbook/client/apis/system/launch.html) pertaining to launching widgets.

There is a snippet at the bottom regarding opening a widget with launch data when the widget metadata isn't provided from the server (user's bookmarks). You simply append the uriencoded launchData to the query params of the widget being opened. And open the widget with normal browser technology, i.e. `window.open`

**Comment by tonyalletag** [comment]
http://ozone-development.github.io/ozp-iwc/1.2.2/gitbook/client/apis/system/launch.html

[12:31] 
var bouncingBallsRef = new iwc.system.Reference("/applicatin/com.ozp.bouncingBalls");

bouncingBallsRef.launch();
