### ISSUE TITLE
IWC Intents should be able to offer widgets not actively running

### ISSUE THREAD

**Issue by itaran** [ozone-development/ozp-iwc#386]
Currently in OZP, Widget X fires an intent and the selection of widgets that can display that intent is limited to widgets that have been launched.  The list of widgets should encompass ALL widgets that support that intent whether they are launched, bookmarked but not launched, or exists in the marketplace but may not have been bookmarked.

**Comment by Kevin-K** [comment]
>The list of widgets should encompass ALL widgets that support that intent whether they are launched, bookmarked but not launched, or exists in the marketplace but may not have been bookmarked.

Noted on #385, but unfortunately the Ozone Team dropped intent registration data from it's backend support. 

The IWC is developed to launch applications to handle intents if their application listing data on the backend supplies metadata pertaining to the intents.

[listing schema here](http://ozone-development.github.io/ozp-iwc/1.2.1/gitbook/bus/endpoints/application.html) (search for application/vnd.ozp-iwc-application-v1+json)

If the supplied data from the backend for an application does not provide intent data, the application cannot be opened to handle the intent.

If the intent data is supplied (Ozone Backend does not supply it), the intent chooser will open with the selection of applications to open.

If this is a desired functionality open  an issue on the [community-request repo](https://github.com/ozone-development/ozp-community-request/issues) and reference this issue for backstory.
