### ISSUE TITLE
Update website/materials with new IWC graphics

### ISSUE THREAD

**Issue by bhalt** [ozone-development/ozp-iwc#391]
![iwc diagrams_image](https://cloud.githubusercontent.com/assets/8047457/13112416/8f372838-d558-11e5-9031-3759df3c26ca.png)

--

![iwc diagrams_text](https://cloud.githubusercontent.com/assets/8047457/13112417/8f38f60e-d558-11e5-964d-77481832b677.png)

**Comment by blaino** [comment]
I shouldn't be lurking around here anymore, but this graphic is pretty freaking sweet.

**Comment by Kevin-K** [comment]
Added them to gh-pages, images are `infographic_full.png` and `infographic_min.png`.

Put the full size up on the [homepage](http://ozone-development.github.io/ozp-iwc/1.2.2/)
[de93b15](https://github.com/ozone-development/ozp-iwc/commit/de93b15f2e23b38c7627ebe7ae74e25009d64d5f)

Re open if you need me to change anything!

**Comment by bhalt** [comment]
haha @blaino, we expect you to lurk.
@Kevin-K - that's perfect, thanks!

**Comment by SOAP1914** [comment]
Love the graphic @bhalt, Lmbo @blaino, and Hi :hand: @Kevin-K lol
